# Full syllabus text (as printed in the JSS University MCA 2025-26 syllabus PDF)
# Format: subject name -> list of (unit label, hours, unit title, full topics text)

FULL_SYLLABUS = {

"Fundamentals of Mathematics for Computer Applications": [
 ("Unit I", 8, "Linear Systems and Matrices", "Complex matrices, Hermitian, Skew-Hermitian, Unitary matrices, Elementary transformation, Inverse of a matrix, Echelon forms, Rank of matrix, Solution of linear systems, Characteristic equation, Cayley-Hamilton theorem, Eigen values and eigenvectors."),
 ("Unit II", 8, "Set Theory and Relations", "Set Theory: Sets, Operations on sets, Cardinality of sets, inclusion-exclusion principle, pigeon hole principle. Relations: Relations and Their Properties, n-ary Relations and Their Application, Representing Relations, Closures of Relations, Equivalence Relations, Partial Orderings."),
 ("Unit III", 8, "Mathematical Logic", "Propositional Logic, Applications of Propositional Logic, Propositional Equivalences, Predicates and Quantifiers, Nested Quantifiers, Rules of Inference, Introduction to Proofs."),
 ("Unit IV", 8, "Graph Theory", "Graphs and Graph models, Graph Terminology and Special Types of Graphs, Representing Graphs and Graph Isomorphism, Connectivity, Euler and Hamilton Paths, Shortest Path Problems, Planar Graphs, Graph Coloring."),
 ("Unit V", 8, "Random Variable and Probability Distribution", "Concept of random variable, discrete probability distributions, continuous probability distributions, Mean, variance and co-variance of Random variables. Binomial and normal distribution, Exponential and normal distribution with mean and variables and problems."),
],

"Programming and Data Structures using C": [
 ("Unit I", 8, "C Fundamentals", "Structure of a C program, compilation and linking processes, Constants, Variables, Data Types, Expressions using operators in C, Managing Input and Output operations, Decision Making and Branching, Looping statements. Arrays - Initialization, Declaration, One dimensional and Two-dimensional arrays. Strings - String operations."),
 ("Unit II", 8, "Functions, Pointers and Basics of Data Structures", "Functions - Pass by value, Pass by reference, Recursion. Pointers - Declaring and Initializing Pointers, Pointer Arithmetic, Function and Pointer Parameters, Pointer and Arrays, Dynamic Memory Allocation, Structures - Defining and using a Structure, Passing Structures to Functions, Structure and Pointers. Basics of Data Structures and Algorithms: Algorithms as a technology, Analyzing algorithms, Growth of Functions, Asymptotic notations, Types of data structures."),
 ("Unit III", 8, "Stacks and Queues", "Stack: Definition, Array representation, Prefix, Infix and Postfix expressions, Utility and conversion of these expressions from one to another. Queue: Definition, Array representation, Types of queues: Simple queue, Circular queue, double ended queue, Priority queue."),
 ("Unit IV", 8, "Linked Lists and Hashing", "Linked List, Inserting and Removing nodes from a list, singly linked List, Doubly Linked List, Linked list Implementation of Stacks. Dictionaries, Hash Table Representation, Hash Functions."),
 ("Unit V", 8, "Non-Linear Data Structures", "Need for non-linear structures, Graphs: Introduction to Graph, Graph Traversal Techniques. Trees: Types of Trees, Binary Tree, Representation of Binary trees using arrays and lists, Binary tree traversals, Binary search trees."),
],

"Python Programming": [
 ("Unit I", 6, "Python Basics and Program Flow Control", "Introduction to Python Basics: Entering Expressions into the Interactive Shell, The Integer, Floating-Point, and String Data Types, String Concatenation and Replication, Storing Values in Variables, Your First Program, Dissecting Your Program. Python Program Flow Control: Conditional blocks: if, else and else if, Simple for loops in python, For loop using ranges, string, list and dictionaries. Use of while loops in python, Loop manipulation using pass, continue, break and else. Programming using Python conditional and loop blocks."),
 ("Unit II", 6, "Strings, Lists, Tuples, Sets and Dictionaries", "Using string data type and string operations, Defining list and list slicing, Use of Tuple data type, String, List, Set and Dictionary, Manipulations, Building blocks of python programs, string manipulation methods, List manipulation, Dictionary manipulation, Programming using string, list and dictionary in-built functions."),
 ("Unit III", 6, "Functions, Functional Programming and Exception Handling", "Def Statements with Parameters, Return Values and return Statements, The None Value, Keyword Arguments and print(), Local and Global Scope, Introduction to functional programming and Lambda function, map, filter and reduce, Iterator and Generator in Python, Exception Handling."),
 ("Unit IV", 6, "File Handling", "Reading files, Writing files in python, Understanding read functions, read(), readline(), readlines(). Understanding write functions, write() and writelines(). Manipulating file pointer using seek. Programming using file operations."),
],

"Database Management System": [
 ("Unit I", 6, "Introduction to Database Systems and the Relational Model", "Database-System Applications, Purpose of Database Systems, View of Data, Database Languages, Relational Databases, Database Design, Data Storage and Querying, Transaction Management, Database Architecture, Data Mining and Information Retrieval, Specialty Databases, Database Users and Administrators, History of Database Systems. Introduction to the Relational Model: Structure of Relational Databases, Database Schema, Keys, Schema Diagrams, Relational Query Languages."),
 ("Unit II", 6, "Entity Relationship Model", "Overview of the Design Process, The Entity Relationship Model, Constraints, Removing Redundant Attributes in Entity Sets, Entity Relationship Diagrams, Reduction to Relational Schemas, Entity-Relationship Design Issues, Extended E-R Features, Other Aspects of Database Design."),
 ("Unit III", 6, "SQL and Intermediate SQL", "Overview of the SQL Query Language, SQL Data Definition, Basic Structure of SQL Queries, Additional Basic Operations, Set Operations, Null Values, Aggregate Functions, Nested Subqueries, Modification of the Database. Intermediate SQL: Join Expressions, Views, Transactions, Integrity Constraints, SQL Data Types and Schemas."),
 ("Unit IV", 6, "Advanced SQL and Relational Query Languages", "Accessing SQL from a Programming Language, Functions and Procedures, Triggers, Recursive Queries, Advanced Aggregation Features, OLAP. Formal Relational Query Languages: The Relational Algebra, The Tuple Relational Calculus."),
 ("Unit V", 6, "Relational Database Design and Normalization", "Features of Good Relational Design, Atomic Domains and First Normal Form, Decomposition Using Functional Dependencies, Functional Dependency Theory, Algorithm for Decomposition, Decomposition Using Multivalued Dependencies, More Normal Forms, Database-Design Process."),
],

"Operating System with Linux": [
 ("Unit I", 6, "OS Concepts and Process Management", "Operating System concepts: Types of Operating Systems, Operating System Components & Services, System calls. Process Management: Process Concept, Process Scheduling, Threads, CPU Scheduling Criteria, Scheduling algorithm. The Critical Section Problem, Semaphores, Classical problems of synchronization, Monitors."),
 ("Unit II", 6, "Deadlocks and Memory Management", "Deadlocks - system model, Characterization, Deadlock prevention, avoidance and detection, Recovery from deadlock. Memory Management: Logical and Physical address space, Swapping, Contiguous allocation, Paging, Segmentation, Segmentation with paging, Virtual memory - Demand paging and its performance, Page replacement algorithms, Allocation of frames, Thrashing."),
 ("Unit III", 6, "File System", "File System: Concept of a file, access methods, directory structure, file system mounting, file sharing, protection. File system implementation: file system structure, file system implementation, directory implementation, allocation methods, free-space management, efficiency and performance."),
 ("Unit IV", 6, "I/O System", "I/O System: Mass storage structure - overview of mass storage structure, disk structure, disk attachment, disk scheduling algorithms, swap space management, stable storage implementation, tertiary storage structure."),
 ("Unit V", 6, "Introduction to Linux and Shell Scripting", "Introduction and interacting with shell and Desktop to Linux: History, salient features, Linux system architecture, Linux command format, Linux internal and external commands, Directory commands, File related commands, Disk related commands. The Linux Shell Basic commands: cls, cat, cal, date, calendar, who, printf, tty, sty, uname, passwd, echo, tput, bc, script, spell and ispell. Introduction to Shell Scripting, Shell Scripts, read, Command Line Arguments, Exit Status of a Command."),
],

"Communication & Social Skills for Professional Development": [
 ("Unit I", 4, "Process of Communication", "Introduction, Process of Communication, Language as a Tool, Levels of Communication, Communication Networks, Importance of Technical Communication. Definition of Noise, rehousing in strategic Decision Making."),
 ("Unit II", 4, "Impact of Technology on Communication", "Impact of Technology, Software for Creating Messages, Software for Writing Documents, Software for Presenting Documents, Transmitting Documents."),
 ("Unit III", 4, "Effective Presentation", "Effective Presentation: Introduction, Defining purpose, Analyzing Audience and Locale, Organizing Contents, preparing outline, Visual Aids, Kinesics, Proxemics, Paralinguistic, Chronemics, Sample speech."),
 ("Unit IV", 4, "Ethics and the Illusion of Communication", "What are Ethics: Definition of ethics, Importance of Integrity, Ethics in the Business world. The illusion of communication: Failing to confirm the message, Forgetting the call to action, Fearing to disagree, Ignoring the beauty of arguments, choosing the wrong medium, Danger of half-baked ideas, the Art of explanation; word selection, Game played people with truth, Faces of 'no'."),
 ("Unit V", 4, "Professional Ethics in IT", "Professional, The ethics behavior of IT professionals, IT users: Supporting the ethical practices of IT users."),
],

"Object Oriented Programming using Java": [
 ("Unit I", 8, "Introduction, Programming Structures and OOP in Java", "Introduction: Why Java, History of Java, JVM, JRE, Java Environment, Java Source File Structure, and Compilation. Fundamental Programming Structures in Java: Defining Classes in Java, Constructors, Methods, Access Specifiers, Static Members, Final Members, Comments, Data types, Variables, Operators, Control Flow, Arrays & String. Object Oriented Programming: Class, Object, Inheritance, Super Class, Sub Class, Overriding, Overloading, Encapsulation, Polymorphism, Abstraction, Interfaces, and Abstract Class. Packages: Defining Package, CLASSPATH Setting for Packages, Making JAR Files for Library Packages, Import and Static Import, Naming Convention for Packages."),
 ("Unit II", 8, "Exception Handling and Multithreaded Programming", "Exception Handling and Multithreaded Programming: The Idea behind Exception, Exceptions & Errors, Types of Exception, Control Flow in Exceptions, JVM Reaction to Exceptions, Use of try, catch, finally, throw, throws in Exception Handling, In-built and User Defined Exceptions, Checked and Un-Checked Exceptions. Input/Output Basics: Byte Streams and Character Streams, Reading and Writing File in Java. Multithreading: Thread, Thread Life Cycle, Creating Threads, Thread Priorities, Synchronizing Threads, Inter-thread Communication."),
 ("Unit III", 8, "Java New Features", "Java New Features: Functional Interfaces, Lambda Expression, Method References, Stream API, Default Methods, Static Method, Base64 Encode and Decode, For Each Method, Try-with resources, Type Annotations, Repeating Annotations, Java Module System, Diamond Syntax with Inner Anonymous Class, Local Variable Type Inference, Switch Expressions, Yield Keyword, Text Blocks, Records, Sealed Classes."),
 ("Unit IV", 8, "Java Collections Framework", "Java Collections Framework: Collection in Java, Collection Framework in Java, Hierarchy of Collection Framework, Iterator Interface, Collection Interface, List Interface, Array List, Linked List, Vector, Stack, Queue Interface, Set Interface, Hash Set, Linked Hash Set, Sorted Set Interface, Tree Set, Map Interface, Hash Map Class, Linked Hash Map Class, Tree Map Class, Hash table Class, Sorting, Comparable Interface, Comparator Interface, Properties Class in Java."),
 ("Unit V", 8, "Java Collections Framework (as printed in syllabus)", "Java Collections Framework: Collection in Java, Collection Framework in Java, Hierarchy of Collection Framework, Iterator Interface, Collection Interface, List Interface, Array List, Linked List, Vector, Stack, Queue Interface, Set Interface, Hash Set, Linked HashSet, Sorted Set Interface, Tree Set, Map Interface, Hash Map Class, Linked Hash Map Class, Tree Map Class, Hash table Class, Sorting, Comparable Interface, Comparator Interface, Properties Class in Java. (Course Outcome 5 also mentions web and RESTful Web Services with Spring Boot using the Spring Framework.)"),
],

"Agile Software Engineering": [
 ("Unit I", 8, "Introduction and SDLC Models", "Introduction: Introduction to Software Engineering, Software Components, Software Characteristics, Software Crisis, Software Engineering Processes, Similarity and Differences from Conventional Engineering Processes, Software Quality Attributes. Software Development Life Cycle (SDLC) Models: Water Fall Model, Prototype Model, Spiral Model, Evolutionary Development Models, Iterative Enhancement Models."),
 ("Unit II", 8, "Software Requirement Specifications and Quality Assurance", "Software Requirement Specifications (SRS): Requirement Engineering Process: Elicitation, Analysis, Documentation, Review and Management of User Needs, Feasibility Study, Information Modeling, Data Flow Diagrams, Entity Relationship Diagrams, Decision Tables, SRS Document, IEEE Standards for SRS. Software Quality Assurance (SQA): Verification and Validation, SQA Plans, Software Quality Frameworks, ISO 9000 Models, SEI-CMM Model."),
 ("Unit III", 8, "Software Design and Metrics", "Software Design: Basic Concept of Software Design, Architectural Design, Low Level Design: Modularization, Design Structure Charts, Pseudo Codes, Flow Charts, Coupling and Cohesion Measures, Design Strategies: Function Oriented Design, Object Oriented Design, Top-Down and Bottom-Up Design. Software Measurement and Metrics: Various Size Oriented Measures: Halstead's Software Science, Function Point (FP) Based Measures, and Cyclomatic Complexity Measures: Control Flow Graphs."),
 ("Unit IV", 8, "Software Testing", "Software Testing: Testing Objectives, Unit Testing, Integration Testing, Acceptance Testing, Regression Testing, Testing for Functionality and Testing for Performance, Top Down and Bottom Up Testing Strategies: Test Drivers and Test Stubs, Structural Testing (White Box Testing), Functional Testing (Black Box Testing), Test Data Suite Preparation, Alpha and Beta Testing of Products. Static Testing Strategies: Formal Technical Reviews (Peer Reviews), Walk Through, Code Inspection, Compliance with Design and Coding Standards."),
 ("Unit V", 8, "Software Maintenance and Project Management", "Software Maintenance and Software Project Management: Software as an Evolutionary Entity, Need for Maintenance, Categories of Maintenance: Preventive, Corrective and Perfective Maintenance, Cost of Maintenance, Software Re-Engineering, Reverse Engineering. Software Configuration Management Activities, Change Control Process, Software Version Control, An Overview of CASE Tools. Estimation of Various Parameters such as Cost, Efforts, Schedule/Duration, Constructive Cost Models (COCOMO), Resource Allocation Models, Software Risk Analysis and Management."),
],

"Advance Design and Analysis of Algorithms": [
 ("Unit I", 8, "Introduction, Sorting and Order Statistics", "Introduction: Algorithms, analyzing algorithms, Complexity of algorithms, Growth of functions, Performance measurements, Sorting and order Statistics - Shell sort, Quick sort, Merge sort, Heap sort, Comparison of sorting algorithms, Sorting in linear time."),
 ("Unit II", 8, "Advanced Data Structures", "Advanced Data Structures: Red-Black trees, B-trees, Binomial Heaps, Fibonacci Heaps, Tries, skip list."),
 ("Unit III", 8, "Divide and Conquer, Greedy Methods", "Divide and Conquer with Examples such as Sorting, Matrix Multiplication, Convex hull and Searching. Greedy methods with Examples such as Optimal Reliability Allocation, Knapsack, Minimum Spanning trees - Prim's and Kruskal's algorithms, Single source shortest paths - Dijkstra's and Bellman Ford algorithms."),
 ("Unit IV", 8, "Dynamic Programming, Backtracking, Branch and Bound", "Dynamic Programming with Examples such as Knapsack. All pair shortest paths - Warshall's and Floyd's algorithms, Resource allocation problem. Backtracking, Branch and Bound with examples such as Travelling Salesman Problem, Graph Coloring, n-Queen Problem, Hamiltonian Cycles and Sum of subsets."),
 ("Unit V", 8, "Selected Topics", "Selected Topics: Algebraic Computation, Fast Fourier Transform, String Matching, Theory of NP-completeness, Approximation algorithms and Randomized algorithms."),
],

"Web Development": [
 ("Unit I", 8, "Introduction, HTML and XML", "Introduction: Introduction and Web Development Strategies, History of Web and Internet, Protocols Governing Web, Writing Web Projects, Connecting to Internet, Introduction to Internet services and tools, Introduction to client-server computing. Web Page Designing: HTML: List, Table, Images, Frames, forms. XML: Document type definition (DTD), XML schemas, Object Models, presenting and using XML, Using XML Processors: DOM and SAX."),
 ("Unit II", 8, "CSS", "CSS: Creating Style Sheet, CSS Properties, CSS Styling (Background, Text Format, Controlling Fonts), Working with block elements and objects, Working with Lists and Tables, CSS Id and Class, Box Model (Introduction, Border properties, Padding Properties, Margin properties). CSS Advanced (Grouping, Dimension, Display, Positioning, Floating, Align, Pseudo class, Navigation Bar, Image Sprites, Attribute selector), CSS Color, Creating page Layout and Site Designs."),
 ("Unit III", 8, "JavaScript, AJAX and Networking", "Scripting: JavaScript: Introduction, documents, forms, statements, functions, objects, introduction to AJAX. Networking: Internet Addressing, InetAddress, Factory Methods, Instance Methods, TCP/IP Client Sockets, URL, URL Connection, TCP/IP Server Sockets, and Datagram."),
 ("Unit IV", 8, "Enterprise Java Beans, Node.js and MongoDB", "Enterprise Java Bean: Creating a JavaBeans, JavaBeans Properties, Types of beans, Stateful Session bean, Stateless Session bean, Entity bean. Node.js: Introduction, Environment Setup, REPL Terminal, NPM (Node Package Manager), Callbacks Concept, Events, Packaging, Express Framework, Restful API. Node.js with MongoDB: MongoDB Create Database, Create Collection, Insert, delete, update, join, sort, query."),
 ("Unit V", 8, "Servlets and JSP", "Servlets: Servlet Overview and Architecture, Interface Servlet and the Servlet Life Cycle, Handling HTTP get Requests, Handling HTTP post Requests, Redirecting Requests to Other Resources, Session Tracking, Cookies, Session Tracking with HttpSession. Java Server Pages (JSP): Introduction, Java Server Pages Overview, A First Java Server Page Example, Implicit Objects, Scripting, Standard Actions, Directives, Custom Tag Libraries."),
],

"Entrepreneurship & Business Basics": [
 ("Unit I", 5, "Concept and Definitions of Entrepreneurship", "Concept and Definitions: Entrepreneurship, Traits and Qualities of Entrepreneurs, Entrepreneurship process; Theories of entrepreneurship; Factors affecting the emergence of entrepreneurship; Role of an entrepreneur in economic growth as an innovator."),
 ("Unit II", 5, "Classification and Types of Entrepreneurs", "Classification and Types of Entrepreneurs: Social Entrepreneurship; Corporate Entrepreneurs, Family Business: Concept, structure, and kinds of family firms; Culture and evolution of family firm; Managing Business, Industry Types: Primary, Secondary, Tertiary."),
 ("Unit III", 5, "Resource Mobilization", "Resources mobilization, types of resources, Process of resource mobilization, Arrangement of funds, Traditional sources of financing, Venture capital, Angel investors, Business Incubators."),
 ("Unit IV", 5, "Business Structures and E-Business", "Difference between Private Company and Public Company, Role of Sole Trading company and Partnership Firm, Distinguish between Partnership, Co-operative society and Joint Stock Companies. Benefits of E-Business. Limitations of E-Business: Meaning of online transaction and Types of On-line payment mechanism."),
],

"Financial Technologies": [
 ("Unit I", 8, "Introduction to Financial Technology", "Introduction to Financial Technology: Financial technology brief history, Evolution of financial Technologies, Challenges in Financial technologies, Infrastructural needs, Financial Applications in banking, share market and insurance sector."),
 ("Unit II", 8, "Core Banking Solution", "Core Banking Solution: Introduction and benefits of CBS, Evolution of CBS, CBS infrastructure, CBS Modules (HO and Branch modules), Delivery Channels, Market Trends in CBS implementation, Challenges in CBS implementation."),
 ("Unit III", 8, "Electronic Payment Systems", "Electronic Payment Systems: Introduction and working of electronic payment systems, electronic payment Types, E-currency (Crypto-currency and digital cash), Mobile/digital wallets, Payment gateways, Challenges in electronic payment systems."),
 ("Unit IV", 8, "Emerging Trends in Financial Technologies", "Emerging Trends in Financial Technologies: Applications of AI for financial services, Applications of Block-chain Technology for financial services, financial institutions and cloud-based offering, Deception technology, IoT based customized products for financial Services."),
 ("Unit V", 8, "FinTech Regulation and RegTech", "FinTech Regulation and RegTech: Introduction - FinTech Regulations, Evolution of RegTech, RegTech Ecosystem: Financial Institutions, RegTech Ecosystem Ensuring Compliance from the Start: Suitability and Funds, RegTech Startups: Challenges."),
],

"Computer Graphics": [
 ("Unit I", 8, "Raster Graphics Algorithms", "Basic raster graphics algorithms for drawing 2D Primitives: lines, circles, ellipses, arcs, clipping, clipping circles, ellipses & polygon."),
 ("Unit II", 8, "3D Modeling, Transformations and Graphics Hardware", "Polygon Meshes in 3D, curves, cubic & surfaces, Solid modeling. Geometric Transformation: 2D, 3D transformations, window to viewport transformations, achromatic and color models. Graphics Hardware: Hardcopy & display techniques, Input devices, image scanners."),
 ("Unit III", 8, "Shading and Visible Surface Determination", "Shading Techniques: Transparency, Shadows, Object reflection, Gouraud & Phong shading techniques. Visible surface determination techniques for visible line determination, Z-buffer algorithm, scanline algorithm, algorithm for octrees, algorithm for curved surfaces, visible surface ray-tracing, recursive ray tracing, radiosity methods."),
 ("Unit IV", 8, "Image Processing and Procedural Models", "Elementary filtering techniques, elementary Image Processing techniques, Geometric & multi-pass transformation mechanisms for image storage & retrieval. Procedural models, fractals, grammar-based models, multi-particle system, volume rendering."),
 ("Unit V", 8, "Multimedia", "Multimedia: Introduction to Multimedia: Classification of Multimedia, Multimedia Software, Components of Multimedia - Audio: Analog to Digital conversion, sound card fundamentals, Audio play backing and recording. Video, Text: Hypertext, Hypermedia and Hypergraphics, Graphics and Animation: Classification of Animation."),
],

"Data Communication and Computer Networks": [
 ("Unit I", 8, "Data Communications and Network Models", "Data Communications: Components, Data Representation, Data Flow, Networks; Network Criteria, Physical Structures, Network Types: LAN, WAN, Switching. Network Models: Protocol Layering: Principles of Protocol Layering, Logical Connections, TCP/IP Protocol Suite: Layered Architecture, Layers in the TCP/IP Protocol Suite, Addressing, Multiplexing and Demultiplexing, The OSI Model; OSI versus TCP/IP, Lack of OSI Model's Success."),
 ("Unit II", 8, "Physical Layer and Switching", "Introduction to Physical Layer: Data and Signals, Periodic Analog Signals, Digital Signals, Transmission Impairment, Data Rate Limits, Performance. Switching: Circuit-Switched Networks, Packet Switching."),
 ("Unit III", 8, "Data-Link Layer and Network Layer", "Introduction to Data-Link Layer, Link-Layer Addressing: Address Resolution Protocol (ARP). Error Detection and Correction: Introduction, Types of Errors, Redundancy, Detection versus Correction, Coding, Block coding: Error Detection, Cyclic Code: Cyclic Redundancy Check. Introduction to Network Layer: Network-Layer Services: Packetizing, Routing and Forwarding, Packet Switching: Datagram Approach, Virtual-Circuit Approach."),
 ("Unit IV", 8, "Transport Layer and Application Layer", "Introduction to Transport Layer: Transport Layer Services: Transport-Layer Protocols. Introduction to Application Layer, Services, Application-Layer Paradigms, World Wide Web and HTTP, FTP: Two Connections, Control Connection, Data Connection, Security for FTP, E-Mail: Architecture, Web-Based Mail, Domain Name System (DNS): Name Space, DNS in the Internet, Resolution."),
 ("Unit V", 8, "Application Layer Services", "Application Layer: File Transfer, Access and Management, Electronic mail, Virtual Terminals, Other applications. Example Networks - Internet and Public Networks."),
],

"Cryptography and Cyber Security": [
 ("Unit I", 8, "Introduction to Security", "Introduction to Security: Computer Security Concepts, The OSI Security Architecture, Security Attacks, Security Services and Mechanisms, A Model for Network Security. Classical encryption techniques: Substitution techniques, Transposition techniques, Steganography. Foundations of modern cryptography: Perfect security, Information Theory, Product Cryptosystem, Cryptanalysis."),
 ("Unit II", 8, "Symmetric Ciphers", "Symmetric Ciphers: Number theory, Algebraic Structures, Modular Arithmetic, Euclid's algorithm, Congruence and matrices, Group, Rings, Fields, Finite Fields. Symmetric Key Ciphers: SDES, Block Ciphers, DES, Strength of DES, Differential and linear cryptanalysis, Block cipher design principles, Block cipher mode of operation, Evaluation criteria for AES, Pseudorandom Number Generators, RC4, Key distribution."),
 ("Unit III", 8, "Asymmetric Key Cryptography", "Mathematics of Asymmetric Key Cryptography: Primes, Primality Testing, Factorization, Euler's totient function, Fermat's and Euler's Theorem, Chinese Remainder Theorem, Exponentiation and logarithm. Asymmetric Key Ciphers: RSA cryptosystem, Key distribution, Key management, Diffie-Hellman key exchange, Elliptic curve arithmetic, Elliptic curve cryptography."),
 ("Unit IV", 8, "Authentication, Hash Functions and Mutual Trust", "Authentication requirement, Authentication function, MAC, Hash function, Security of hash function: HMAC, CMAC, SHA, Digital signature and authentication protocols, DSS, Schnorr Digital Signature Scheme, ElGamal cryptosystem, Entity Authentication: Biometrics, Passwords, Challenge Response protocols, Authentication applications, Kerberos. Mutual Trust: Key management and distribution, Symmetric key distribution using symmetric and asymmetric encryption, Distribution of public keys, X.509 Certificates."),
 ("Unit V", 8, "Cyber Crime and Information Security", "Cyber Crime and Information Security: classifications of Cyber Crimes, Tools and Methods, Password Cracking, Key loggers, Spywares, SQL Injection, Network Access Control, Cloud Security, Web Security, Wireless Security."),
],

"Machine Learning Techniques": [
 ("Unit I", 8, "Introduction to AI and ML", "Introduction to AI and ML: History of AI, Comparison of AI with Data Science, Need of AI in Mechanical Engineering, Introduction to Machine Learning. Basics: Reasoning, problem solving, Knowledge representation, Planning, Learning, Perception, Motion and manipulation. Types of Machine learning: Supervised, Unsupervised, semi-supervised and reinforcement learning. Feature selection Mechanisms, Data engineering and pre-processing, Data processing cycle, Data processing methods."),
 ("Unit II", 8, "Supervised Learning", "Supervised Learning: Linear Regression, Multiple Regression, Logistic Regression, Classification; classifier models, K Nearest Neighbour (KNN), Naive Bayes, Decision Trees, Support Vector Machine (SVM), Random Forest."),
 ("Unit III", 8, "Unsupervised Learning", "Unsupervised Learning: Dimensionality reduction; Clustering; K-Means clustering; C-means clustering; Fuzzy C-means clustering, EM Algorithm, Association Analysis: Association Rules in Large Databases, Apriori algorithm, Markov models: Hidden Markov models (HMMs)."),
 ("Unit IV", 8, "Reinforcement Learning", "Reinforcement learning: Introduction to reinforcement learning, Methods and elements of reinforcement learning, Bellman equation, Markov decision process (MDP), Q learning, Value function approximation, Temporal difference learning, Applications of Reinforcement learning."),
 ("Unit V", 8, "Neural Networks and Deep Learning Architecture", "Neural Network and Deep Learning architecture: Concept of neural networks, Deep Q Neural Network (DQN), Convolution neural network (CNN): Layers in CNN, CNN architectures. Recurrent Neural Network. Applications: Speech-to-text conversion, Image classification, time series prediction."),
],

"Data Analytics": [
 ("Unit I", 8, "Introduction to Data Analytics and Analytics Lifecycle", "Introduction to Data Analytics: Sources and nature of data, classification of data (structured, semi-structured, unstructured), characteristics of data, introduction to Big Data platform, need of data analytics, evolution of analytic scalability, analytic process and tools, analysis vs reporting, modern data analytic tools, applications of data analytics. Data Analytics Lifecycle: Need, key roles for successful analytic projects, various phases of data analytics lifecycle: discovery, data preparation, model planning, model building, communicating results, operationalization."),
 ("Unit II", 8, "Data Analysis", "Data Analysis: Regression modeling, multivariate analysis, Bayesian modeling, inference and Bayesian networks, support vector and kernel methods, analysis of time series: linear systems analysis & nonlinear dynamics, rule induction, neural networks: learning and generalisation, competitive learning, principal component analysis and neural networks, fuzzy logic: extracting fuzzy models from data, fuzzy decision trees, stochastic search methods."),
 ("Unit III", 8, "Mining Data Streams", "Mining Data Streams: Introduction to streams concepts, stream data model and architecture, stream computing, sampling data in a stream, filtering streams, counting distinct elements in a stream, estimating moments, counting oneness in a window, decaying window, Real-time Analytics Platform (RTAP) applications, Case studies: real time sentiment analysis, stock market predictions."),
 ("Unit IV", 6, "Frequent Itemsets and Clustering", "Frequent Itemsets and Clustering: Mining frequent itemsets, market based modelling, Apriori algorithm, handling large data sets in main memory, limited pass algorithm, counting frequent itemsets in a stream, clustering techniques: hierarchical, K-means, clustering high dimensional data, CLIQUE and ProCLUS, frequent pattern based clustering methods, clustering in non-euclidean space, clustering for streams and parallelism."),
 ("Unit V", 6, "Frameworks and Visualization, Introduction to R", "Frameworks and Visualization: MapReduce, Hadoop, Pig, Hive, HBase, MapR, Sharding, NoSQL Databases, S3, Hadoop Distributed File Systems. Visualization: visual data analysis techniques, interaction techniques, systems and applications. Introduction to R: R graphical user interfaces, data import and export, attribute and data types, descriptive statistics, exploratory data analysis, visualization before analysis, analytics for unstructured data."),
],

"Research Methodology": [
 ("Module I", 8, "Introduction to Research", "Introduction to Research: Concept, Need, and Purpose, Research Problem and Research Design, Literature Review, Hypothesis: Definition, Types, Sources, and Functions."),
 ("Module II", 8, "Types of Research Methods", "Types of Research Methods: Historical, Survey, and Experimental, Case Study, Scientific Research and Statistical Research, etc."),
 ("Module III", 6, "Research Techniques", "Research Techniques and Tools: Questionnaire, Interview, Observation, Schedule and Check-list, etc., Library Records and Reports. Statistics and its Applications, Descriptive Statistics: Measures of Central Tendency & Dispersion, Correlations and linear regression, Chi-Square test, t-test, z-test, f-test. Presentation of Data: Tabular, Graphic, Bar Diagram and Pie Chart, etc. Report Writing."),
 ("Module IV", 8, "Metric Studies and Style Manuals", "Statistical Packages: MS Excel, SPSS, and Web-based Statistical Analysis Tools, etc. Metric Studies and Style Manuals, Scientometrics, Infometrics, and Webometrics, Manual Structure, Style, Contents: ISI, MLA, APA, CHICAGO, etc."),
],

"Cloud Computing": [
 ("Unit I", 8, "Introduction to Cloud Computing", "Introduction to Cloud Computing: Definition of Cloud, Evolution of Cloud Computing, Adoption of cloud-based IT resources, Service Models: Infrastructure-as-a-Service (IaaS), Platform-as-a-Service (PaaS), Software-as-a-Service (SaaS), Deployment models: Public Cloud, Private Cloud, Hybrid Cloud, Community Cloud, Cloud Computing Characteristics."),
 ("Unit II", 8, "Resource Management and Security in Cloud", "Resource Management and Security in Cloud: Inter Cloud Resource Management, Resource Provisioning and Resource Provisioning Methods, Global Exchange of Cloud Resources, Security Overview, Cloud Security Challenges, Software-as-a-Service Security, Security Governance, Virtual Machine Security, IAM, Security Standard."),
 ("Unit III", 8, "Virtualization, Docker and Containers", "Challenges of cloud computing, Virtualization concept, Types of virtualizations, Demo of virtualization, Virtualization Merits, Role of virtualization in cloud computing, Virtualization Demerits, VM Placement, VM Migration, VM Migration Demo, VM clustering, Design Issues in VM Clustering, Need of Dockers and Containers, Docker Eco-System, Hypervisor vs Docker."),
 ("Unit IV", 8, "Cloud Technologies and Advancements", "Cloud Technologies and Advancements: Hadoop: MapReduce, Virtual Box, Google App Engine, Programming Environment for Google App Engine, Open Stack, Federation in the Cloud, Four Levels of Federation, Federated Services and Applications, Future of Federation."),
 ("Unit V", 8, "Case Study: Cloud Security and Big Data", "Case Study: Cloud Market analysis, Security and Compliances, Shared security model in IaaS/PaaS/SaaS, Shared technology issues, Data loss or leakage, Account or service hijacking, Implementation of cloud security, Security Groups, Network Access Control Lists, Cloud databases, Parallel Query Execution with NoSQL Database, Big Data, Handling Big Data on Cloud Platform, Map-Reduce framework for large clusters using Hadoop, Design of data applications based on Map Reduce in Apache Hadoop."),
],

"Block Chain Technology": [
 ("Unit I", 8, "Introduction to Blockchain", "Introduction to Blockchain: Definition, History, and Evolution of Blockchain, Blockchain vs Traditional Databases, Key Characteristics of Blockchain (Decentralization, Immutability, Transparency, Security). Blockchain Components: Blocks, Hashing, and Merkle Trees. Transactions and Ledgers. Peer-to-Peer (P2P) Network. Blockchain Types: Public, Private, and Consortium Blockchains. Use Cases and Applications of Blockchain (Cryptocurrencies, Smart Contracts, Supply Chain, etc.). Overview of Bitcoin: Introduction to Bitcoin and its working. Understanding the concept of mining and consensus in Bitcoin."),
 ("Unit II", 8, "Cryptographic Principles and Blockchain Security", "Cryptographic Principles: Basics of Cryptography: Symmetric vs Asymmetric encryption. Hashing Algorithms (SHA-256, MD5, etc.). Public/Private Key Cryptography. Digital Signatures and Certificates: How digital signatures ensure transaction integrity, Blockchain transaction signing and verification process. Blockchain Security Models: Security issues in blockchain: 51% Attack, Double Spending, Sybil Attacks. Blockchain and Privacy: Zero-knowledge proofs, Ring signatures, Stealth Addresses. Smart Contract Security: Vulnerabilities in Smart Contracts (Reentrancy attacks, Integer overflow, etc.). Best practices in writing secure smart contracts."),
 ("Unit III", 8, "Consensus Algorithms and Scalability", "Overview of Consensus Algorithms: Definition and Importance of Consensus in Blockchain, Proof of Work (PoW), Proof of Stake (PoS), Delegated Proof of Stake (DPoS), Other Consensus Algorithms: Proof of Authority (PoA), Practical Byzantine Fault Tolerance (PBFT), and more. Mining and Validation in Blockchain: Mining process in Proof of Work and its energy concerns. Staking in Proof of Stake and Delegated Proof of Stake. Blockchain Scalability and Performance: Scalability issues in blockchain networks. Layer 2 solutions (e.g., Lightning Network, Plasma, Sharding). Blockchain Network Models: Permissioned vs Permissionless Blockchain networks. Interoperability and Cross-chain communication (e.g., Polkadot, Cosmos)."),
 ("Unit IV", 8, "Smart Contracts, Ethereum and dApps", "Introduction to Smart Contracts: Definition and importance of Smart Contracts in Blockchain. Use cases of Smart Contracts (DeFi, NFT, insurance, etc.). Ethereum Blockchain Platform: Ethereum Overview: Ethereum Virtual Machine (EVM), Gas, Ether. Ethereum Development Frameworks (Truffle, Hardhat). Smart Contract Development: Writing smart contracts in Solidity. Testing and deploying smart contracts on Ethereum testnets. Decentralized Applications (dApps): Introduction to dApps architecture. Building a simple dApp using Ethereum and Smart Contracts."),
 ("Unit V", 8, "Blockchain Applications and Future Trends", "Blockchain in Cryptocurrency: Overview of Bitcoin, Ethereum, and other popular cryptocurrencies, Wallets, Exchanges, and Blockchain Transactions. Enterprise Blockchain Solutions: Blockchain for Supply Chain Management, Healthcare, Voting Systems, and IoT. Case Studies: IBM's Hyperledger, VeChain, and other enterprise blockchain platforms. Blockchain in Government and Public Sector: Blockchain in Digital Identity, Land Records, and Governance. Future of Blockchain: Blockchain 3.0 and beyond: Interoperability, Scalability, and Sustainability. Emerging Trends: Web3, NFTs, DAOs, Metaverse, and more."),
],

"Internet of Things": [
 ("Unit I", 8, "Introduction and Applications", "Introduction and Applications: Introduction to IoT - Definition, Characteristics, functional requirements, motivation, Physical design - things in IoT, IoT protocols, Logical Design - functional blocks, communication models, Communication APIs, M2M Communication, IoT Examples. Design Principles for Connected Devices: IoT/M2M systems layers and design standardization, communication technologies, data enrichment and consolidation, ease of designing and affordability. Applications: Home Automation, Cities, Environment, Energy, Agriculture, Health, Industry."),
 ("Unit II", 8, "Hardware for IoT", "Hardware for IoT: Sensors, Digital sensors, actuators, radio frequency identification (RFID) technology, wireless sensor networks, participatory sensing technology. Embedded Platforms for IoT: Embedded computing basics, Overview of IoT supported Hardware platforms such as Arduino, NetArduino, Raspberry Pi, Beagle Bone, Intel Galileo boards and ARM Cortex."),
 ("Unit III", 8, "Developing Internet of Things", "Developing Internet of Things: IoT Methodology - Purpose & Requirements specification, process specification, domain model specification, information model specification, service specification, IoT level specifications."),
 ("Unit IV", 8, "Programming the Arduino", "Programming the Arduino: Arduino Platform Boards Anatomy, Arduino IDE, coding, using emulator, using libraries, additions in Arduino, programming the Arduino for IoT."),
 ("Unit V", 8, "Case Study on IoT System", "Case Study on IoT System: Case study for weather monitoring system - modules & package of Python, Python packages of interest for IoT: JSON, XML, HTTP & URLLib, SMTPLib. Exemplary device: Raspberry Pi, Linux on Raspberry Pi."),
],

"Data Warehousing and Data Mining": [
 ("Unit I", 8, "Data Warehousing and Business Analysis", "Data Warehousing and Business Analysis: Data warehousing Components, Building a Data warehouse, Data Warehouse Architecture, DBMS Schemas for Decision Support, Data Extraction, Cleanup, and Transformation Tools, Metadata, reporting, Query tools and Applications, Online Analytical Processing (OLAP), OLAP and Multidimensional Data Analysis."),
 ("Unit II", 8, "Data Mining and Association Rule Mining", "Data Mining: Data Mining Functionalities, Data Preprocessing, Data Cleaning, Data Integration and Transformation, Data Reduction, Data Discretization and Concept Hierarchy Generation, Architecture of a Typical Data Mining System, Classification of Data Mining Systems. Association Rule Mining: Efficient and Scalable Frequent Itemset Mining Methods, Mining Various Kinds of Association Rules, Association Mining to Correlation Analysis, Constraint-Based Association Mining."),
 ("Unit III", 8, "Classification and Prediction", "Classification and Prediction: Issues Regarding Classification and Prediction, Classification by Decision Tree Introduction, Bayesian Classification, Rule Based Classification, Classification by Back propagation, Support Vector Machines, Associative Classification, Lazy Learners, Other Classification Methods, Prediction, Accuracy and Error Measures, Evaluating the Accuracy of a Classifier or Predictor, Ensemble Methods, Model Selection."),
 ("Unit IV", 8, "Cluster Analysis", "Cluster Analysis: Types of Data in Cluster Analysis, A Categorization of Major Clustering Methods, Partitioning Methods, Hierarchical methods, Density-Based Methods, Grid-Based Methods, Model-Based Clustering Methods, Clustering High-Dimensional Data, Constraint-Based Cluster Analysis, Outlier Analysis."),
 ("Unit V", 8, "Mining Object, Spatial, Multimedia, Text and Web Data", "Mining Object, Spatial, Multimedia, Text and Web Data: Multidimensional Analysis and Descriptive Mining of Complex Data Objects, Spatial Data Mining, Multimedia Data Mining, Text Mining, Mining the World Wide Web."),
],

"Prompt Engineering": [
 ("Unit I", 8, "Introduction to Large Language Models", "Introduction to Large Language Models: What are Text Generation Models, Large Language Models are Magic, A Brief History of Language Models, LLMs in the Market."),
 ("Unit II", 8, "Understanding Prompting and Prompt Techniques", "Understanding Prompting and Prompt Techniques: Five Principles of Prompting, Introducing LLM Prompts, How LLM Prompts Work, Types of Prompts, Components of a Prompt, Defining Personality in Prompts, Mix and Match: Strategic Combination for Enhanced Prompts, Challenges and Limitations of Using Prompts."),
 ("Unit III", 8, "Standard Practices for Text Generation", "Standard Practices for Text Generation: Generating Lists, Explain It Like I'm Five, Universal Translation Through LLMs, Ask For Context, Text Style Unbundling, Identifying the Desired Textual Features, Generating New Content with the Extracted Features, Role Prompting, Analyzing Existing Prompts for Strengths and Weaknesses."),
 ("Unit IV", 8, "Generating Text with AI for Content Creation", "Generating Text with AI for Content Creation: Using AI for Copywriting, Creating Social Media Posts, Writing Video Scripts, Using AI for Personalized Messaging, Creating Engaging and Tailored Content with AI, Techniques for Crafting Effective Prompts for Surveys, Assessments, and Data Collection, Using Prompts in Research Methodology."),
 ("Unit V", 8, "Diffusion Models for Image Generation", "Introduction to Diffusion Models for Image Generation: Introduction to Image Generation with AI, Principles of Designing Prompts for Image Generation, Available Models: OpenAI DALL-E, Midjourney, Stable Diffusion, Google Gemini, Text to Video, Model Comparison, Reverse Engineering Prompts, Negative Prompts, Prompt Re-Writing, Prompt Analysis."),
],

"Natural Language Processing": [
 ("Unit I", 8, "Overview and Morphology", "Overview and Morphology: Introduction, Models and Algorithms, Regular Expressions, Basic Regular Expression Patterns, Finite State Automata. Morphology: Inflectional Morphology, Derivational Morphology, Finite-State Morphological Parsing, Porter Stemmer."),
 ("Unit II", 8, "Word Level and Syntactic Analysis", "Word Level and Syntactic Analysis: N-gram Models of Syntax, Counting Words, Unsmoothed N-grams, Smoothing, Back-off, Deleted Interpolation, Entropy, English Word Classes, Tag sets for English, Part of Speech Tagging: Rule Based, Stochastic, Transformation-Based Tagging."),
 ("Unit III", 8, "Context Free Grammars", "Context Free Grammars: Context Free Grammars for English Syntax, Context-Free Rules and Trees, Sentence-Level Constructions, Agreement, Sub Categorization. Parsing: Top-down, Early Parsing, Feature Structures, Probabilistic Context-Free Grammars."),
 ("Unit IV", 8, "Semantic Analysis", "Semantic Analysis: Representing Meaning, Meaning Structure of Language, First Order Predicate Calculus, Representing Linguistically Relevant Concepts, Syntax-Driven Semantic Analysis, Semantic Attachments, Syntax-Driven Analyzer. Robust Analysis, Lexemes and Their Senses, Internal Structure, Word Sense Disambiguation, Information Retrieval."),
 ("Unit V", 8, "Language Generation and Discourse Analysis", "Language Generation and Discourse Analysis: Discourse, Reference Resolution, Text Coherence, Discourse Structure, Coherence. Dialog and Conversational Agents: Dialog Acts, Interpretation, Conversational Agents. Language Generation: Architecture, Surface Realizations, Discourse Planning. Machine Translation: Transfer Metaphor, Interlingua, Statistical Approaches."),
],

"Mobile Application Development": [
 ("Unit I", 8, "Introduction to Android", "Introduction to Android: The Android Platform, Android SDK, Eclipse Installation, Android Installation, Building your First Android application, Understanding Anatomy of Android Application, Android Manifest file."),
 ("Unit II", 8, "Android Application Design Essentials", "Android Application Design Essentials: Anatomy of an Android application, Android terminologies, Application Context, Activities, Services, Intents, Receiving and Broadcasting Intents, Android Manifest File and its common settings, Using Intent Filter, Permissions."),
 ("Unit III", 8, "Android User Interface Design Essentials", "Android User Interface Design Essentials: User Interface Screen elements, Designing User Interfaces with Layouts, Drawing and Working with Animation."),
 ("Unit IV", 8, "Testing and Publishing Android Applications", "Testing: Android applications, Publishing Android application, Using Android preferences, Managing Application resources in a hierarchy, working with different types of resources."),
 ("Unit V", 8, "Using Common Android APIs", "Using Common Android APIs: Using Android Data and Storage APIs, Managing data using SQLite, Sharing Data between Applications with Content Providers, Using Android Networking APIs, Using Android Web APIs, Using Android Telephony APIs, Deploying Android Application to the World."),
],

"Distributed System": [
 ("Unit I", 8, "Characterization of Distributed Systems", "Characterization of Distributed Systems: Introduction, Examples of distributed Systems, Resource sharing and the Web, Challenges. Architectural models, Fundamental Models. Theoretical Foundation for Distributed System: Limitation of Distributed system, absence of global clock, shared memory, Logical clocks, Lamport's & vector logical clocks. Concepts in Message Passing Systems: causal order, total order, total causal order, Techniques for Message Ordering, Causal ordering of messages, global state, termination detection."),
 ("Unit II", 8, "Propositional Logic and Proof Techniques", "Propositional Logic and Proof Techniques: Propositions, Logical operations, Truth tables, Logical equivalence and laws of logic (De Morgan's laws, distributive, associative, etc.), Predicates and quantifiers, Rules of inference, Proof techniques (Direct proof, proof by contradiction, proof by contraposition)."),
 ("Unit III", 8, "Consensus and Recovery", "Consensus and Recovery: Consensus and Agreement Algorithms: Problem Definition, Overview of Results, Agreement in a Failure-Free System (Synchronous and Asynchronous), Agreement in Synchronous Systems with Failures. Checkpointing and Rollback Recovery: Introduction, Background and Definitions, Issues in Failure Recovery, Checkpoint-based Recovery, Coordinated Checkpointing Algorithm, Algorithm for Asynchronous Checkpointing and Recovery."),
 ("Unit IV", 8, "Transactions and Concurrency Control", "Transactions and Concurrency Control: Introduction, Transactions, Nested Transactions, Locks, Optimistic Concurrency Control, Timestamp Ordering, Comparison of Methods for Concurrency Control. Distributed Transactions: Introduction, Flat and Nested Distributed Transactions, Atomic Commit Protocols, Concurrency Control in Distributed Transactions, Distributed Deadlocks, Transaction Recovery."),
 ("Unit V", 8, "Distributed File Systems, Name Services and Shared Memory", "Distributed File Systems: Introduction, File Service Architecture, Case Study 1: Sun Network File System, Case Study 2: The Andrew File System. Name Services: Introduction, Name Services and the Domain Name System, Directory Services, Case Study of the Global Name Services. Distributed Shared Memory: Introduction, Design and Implementation Issues, Sequential Consistency and IVY case study, Release Consistency, Munin Case Study, Other Consistency Models."),
],

}
